platform :ios, "8.0"
inhibit_all_warnings!
use_frameworks!

pod 'SDAutoLayout', '~> 2.1.1'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage', '~>3.7.3'
pod 'SDWebImage-ProgressView'
pod 'AFNetworking', '~> 2.6.3'
pod 'IQKeyboardManager'
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'TTCounterLabel',:git => "https://github.com/TriggerTrap/TTCounterLabel.git"
pod 'TTTAttributedLabel', '~> 1.7.1'
pod 'UITextView+Placeholder'
#pod 'ReactiveCocoa'
#pod 'NJBannerView', '~> 1.0.4'